# Copyright 2016, EMC, Inc.

version: '2'

volumes:
  dhcp-leases:
    external: false

services:

  mongo: # 27017
    image: mongo:2.4
    network_mode: "host"
    privileged: true

  rabbitmq: # 5672, 15672
    image: rabbitmq:management
    network_mode: "host"
    privileged: true

  dhcp: # 67/udp
    image: rackhd/isc-dhcp-server
    network_mode: "host"
    privileged: true
    volumes:
      - "dhcp-leases:/var/lib/dhcp"
      - "./dhcp/config:/etc/dhcp"
      - "./dhcp/defaults:/etc/defaults"

  files:
    image: rackhd/files:devel
    network_mode: "host"
    privileged: true
    volumes:
      - "./files/mount:/RackHD/files"

  dhcp-proxy: # 68/udp, 4011
    depends_on:
      - dhcp
      - mongo
      - rabbitmq
    image: rackhd/on-dhcp-proxy:devel
    privileged: true
    volumes:
      - "dhcp-leases:/var/lib/dhcp"
      - "./monorail:/opt/monorail"

  http: # 9090, 9080
    depends_on:
      - files
      - mongo
      - rabbitmq
    image: rackhd/on-http:devel
    network_mode: "host"
    privileged: true
    volumes:
      - "./files/mount/common:/RackHD/on-http/static/http/common"
      - "./monorail:/opt/monorail"


  syslog: # 514/udp
    depends_on:
      - mongo
      - rabbitmq
    image: rackhd/on-syslog:devel
    network_mode: "host"
    privileged: true
    volumes:
      - "./monorail:/opt/monorail"

  taskgraph:
    depends_on:
      - dhcp
      - mongo
      - rabbitmq
      - syslog
    image: rackhd/on-taskgraph:devel
    network_mode: "host"
    privileged: true
    volumes:
      - "./monorail:/opt/monorail"

  tftp: # 69/udp
    build: "../on-tftp"
    depends_on:
      - files
      - mongo
      - rabbitmq
      - syslog
    image: rackhd/on-tftp:devel
    network_mode: "host"
    privileged: true
    volumes:
      - "./files/mount:/RackHD/on-tftp/static/tftp"
      - "./monorail:/opt/monorail"


